name: pulpnow
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61171
title: PULP Now
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050708'
    - '#f6851f'
    - '#ef5123'
    - '#d81c55'
    - '#5f3610'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
