name: pulpnow
favicon: null
layout_spectrum: 0.43396
typography_spectrum: 0.61171
title: PULP Now - A Digital Daily for Colorado
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-56385421-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050708'
    - '#f6851f'
    - '#ef5123'
    - '#d81c55'
    - '#5f3610'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
