name: pulpnow
favicon: null
layout_spectrum: 0.4197
typography_spectrum: 0.61171
title: PULP Now - The Web Freshly Squeezed
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-56385421-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff8700'
    - '#ffbe00'
    - '#ffe268'
    - '#f60000'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
